class UIConfig:
    WINDOW_WIDTH = 1360
    WINDOW_HEIGHT = 820
    WINDOW_MIN_WIDTH = 1180
    WINDOW_MIN_HEIGHT = 760

    COL_COUNT = 1

    MAIN_PAD = 16
    SECTION_PAD_X = 24
    SECTION_PAD_Y = 16
    INNER_PAD = 18
    SMALL_PAD = 12
    XSMALL_PAD = 8

    LEFT_PANEL_WIDTH = 320
    NAV_PANEL_HEIGHT = 320
    THUMB_IMAGE_SIZE = (72, 72)
    THUMB_CARD_WIDTH = 230
    THUMB_CARD_HEIGHT = 84
    THUMB_TEXT_WRAP = 120

    BUTTON_HEIGHT = 40
    SMALL_BUTTON_HEIGHT = 34
    PRIMARY_BUTTON_HEIGHT = 42
    BUTTON_CORNER = 12

    OUTER_CORNER = 24
    PANEL_CORNER = 22
    CARD_CORNER = 20
    GROUP_CORNER = 18
    SMALL_CORNER = 14
    XS_CORNER = 10

    BORDER_WIDTH = 1
    TREE_ROW_HEIGHT = 32
    VALUE_LABEL_WIDTH = 60

    PREVIEW_MIN_WIDTH = 420
    PREVIEW_MIN_HEIGHT = 320
    PREVIEW_IMAGE_PAD = 40
    PREVIEW_PANE_MIN_HEIGHT = 300
    ACTION_PANE_MIN_HEIGHT = 120
    ACTION_PANE_START_HEIGHT = 210

    FONT_TITLE = 28
    FONT_SECTION = 20
    FONT_GROUP = 16
    FONT_BUTTON = 14
    FONT_BODY = 12
    FONT_SMALL = 10

    COLOR_APP_BG = "#eef3f9"
    COLOR_LEFT_BG = "#f7f9fc"
    COLOR_RIGHT_BG = "#f8fbff"
    COLOR_CARD_BG = "#ffffff"
    COLOR_STAGE_BG = "#edf3fb"
    COLOR_SUBTLE_BG = "#f4f7fb"
    COLOR_ACCENT_BG = "#eaf1fb"

    COLOR_BORDER = "#d7deea"
    COLOR_BORDER_SOFT = "#dbe3ef"
    COLOR_PRIMARY = "#2563eb"
    COLOR_PRIMARY_HOVER = "#1d4ed8"
    COLOR_PRIMARY_SOFT = "#dbeafe"
    COLOR_PRIMARY_SOFT_HOVER = "#bfdbfe"
    COLOR_SECONDARY_SOFT = "#e8eef8"
    COLOR_SECONDARY_SOFT_HOVER = "#d9e5f5"
    COLOR_BUTTON_SOFT = "#edf4ff"
    COLOR_BUTTON_SOFT_HOVER = "#dbeafe"

    COLOR_TEXT = "#223041"
    COLOR_TEXT_ALT = "#1f2f40"
    COLOR_TEXT_MUTED = "#7a8797"
    COLOR_TEXT_FAINT = "#8ea0b5"
    COLOR_TEXT_BLUE = "#1d4ed8"
    COLOR_TEXT_BLUE_DARK = "#1e3a5f"

    COLOR_SUCCESS = "#16a34a"
    COLOR_SUCCESS_HOVER = "#15803d"
    COLOR_NEUTRAL = "#e5eaf2"
    COLOR_NEUTRAL_HOVER = "#d8e0eb"
    COLOR_DANGER = "#ef4444"

    RGB_COLORS = ["#ef4444", "#16a34a", "#2563eb"]
    RGB_TITLES = ["Red Layer", "Green Layer", "Blue Layer"]
